### ISSUE TITLE
Issues installing plotpot using provided pip instructions

### ISSUE THREAD

**Issue by darkwraith** [ahpohl/plotpot#3]
The provided installation instructions worked for me up until I tried to do the pip install:

>   Could not find a version that satisfies the requirement plotpot (from versions: )
> No matching distribution found for plotpot

This code worked instead:
pip install git+git://github.com/ahpohl/plotpot

**Comment by ahpohl** [comment]
not published to pyhton package index yet so pip cannot find it. WIP. thanks for sharing the pip download directly from github.

**Comment by ahpohl** [comment]
published source to PyPI. `pip install plotpot` should work now

**Comment by ahpohl** [comment]
closing this issue as pip install is now working
