### ISSUE TITLE
Import success but no graph produced

### ISSUE THREAD

**Issue by darkwraith** [ahpohl/plotpot#4]
When I run a basic plotpot on the test file the import is successful with a sql file generated successfully and a summary of the data presented but it wont plot the data

`plotpot show arbintest.res`
Produces this error:

> Output filename: arbintest.sqlite
> Traceback (most recent call last):
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\Scripts\plotpot-script.py", line 11, in <module>
>     load_entry_point('plotpot==1.0.1.dev11+g692fb7c', 'console_scripts', 'plotpot')()
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\__main__.py", line 86, in main
>     Plotpot(args)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\plotpot.py", line 14, in __init__
>     self.runSubcommands()
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\plotpot.py", line 21, in runSubcommands
>     self.subcommandShow()
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\plotpot.py", line 52, in subcommandShow
>     plotObj = Plot(self.args)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\plot.py", line 28, in __init__
>     super().__init__(args)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\data.py", line 29, in __init__
>     self.metaInfo = self.updateMetaInfo()
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\data.py", line 129, in updateMetaInfo
>     jourObj = Journal(self.args)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\journal.py", line 14, in __init__
>     self.journalPath = self.getJournalPath()
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\site-packages\plotpot\journal.py", line 31, in getJournalPath
>     journalFullPath = os.path.join(os.path.dirname(sys.argv[0]), journalPath)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\ntpath.py", line 114, in join
>     genericpath._check_arg_types('join', path, *paths)
>   File "C:\Users\jbenson\Anaconda3\envs\plotpot-env\lib\genericpath.py", line 149, in _check_arg_types
>     (funcname, s.__class__.__name__)) from None
> TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by darkwraith** [comment]
Issue solved by correctly setting the convpot, anaconda, and anaconda/scripts folders to path. Screen shot that might help future users can be found here: https://imgur.com/kuRGyNY

**Comment by ahpohl** [comment]
bug fixed in master branch. if plotpot-journal environment is not set, it now looks for the HOME (linux) and  USERPROFILE (windows) environments and creates the journal there.

**Comment by ahpohl** [comment]
close this issue as bug is fixed in v1.0.7
